name: Publish
on:
  release:
    types:
      - published
      - edited

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@main
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-restore -c Release

      - name: Pack
        run: dotnet pack --no-restore -c Release -o ./packages

      - name: Push
        shell: bash
        run: dotnet nuget push ./packages/*.nupkg -k ${{ secrets.NUGET_ACCESS_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-service-endpoint
